### ISSUE TITLE
Patterns for deleting objects

### ISSUE THREAD

**Issue by rossjones** [datagovuk/publish_data_alpha#228]
Having dataset_delete just delete and unindex a dataset without confirmation seems a bit harsh :) Are there any GDS patterns around asking before doing it?

**Comment by maxf** [comment]
Only think I can find is https://designpatterns.hackpad.com/Add-edit-delete-loop-WF8hhDeN6yZ which doesn't answer the question. I'll add it to the list of design crit items

**Comment by rossjones** [comment]
I'm most interested in finding out whether delete happens without confirmation, because that's a bit risky I think as we're doing hard-deletes atm, rather than soft-deletes.

**Comment by maxf** [comment]
TBD by designers

**Comment by BlancaTortajada** [comment]
@maxf @rossjones I thought I'd add the InVision mockup for this issue:
https://projects.invisionapp.com/d/main#/console/10081578/218933707/comments/78256686

While we have deletion for drafts and published datasets, let's have the deletion confirmation loop for both.

**Comment by maxf** [comment]
Implemented delete files/docs with https://github.com/datagovuk/publish_data_alpha/pull/380
Delete dataset upcoming
