### ISSUE TITLE
Can we publish with broken links?

### ISSUE THREAD

**Issue by rossjones** [datagovuk/publish_data_alpha#266]
Not on first publish. On second or later publish, we'd prefer they complete the task rather than block them indefinitely (they might not be able to fix the broken link).

**Comment by gtdata** [comment]
I agree, to improve the quality of data we shouldn't allow users to publish with broken links on the first publish @rossjones @maxf @BlancaTortajada

**Comment by BlancaTortajada** [comment]
Yes, we shouldn't allow publishing with broken links on first publish.

**Comment by rossjones** [comment]
Great, I think we can close this now.
