### ISSUE TITLE
Answer questions about closed organisations

### ISSUE THREAD

**Issue by rossjones** [datagovuk/publish_data_alpha#335]
Where we have existing organisations that have closed and replaced by other departments (e.g. BIS -> BEIS) we currently keep any old datasets so that they are still available.

Do we need to:
* Stop users publishing to closed organisations?
* Stop users joining closed organisations?
* Show in find-data that the organisation is closed and show the new organisation?

**Comment by gtdata** [comment]
as a part of improving the quality of data - we do need to make it easy to show that an organisation is closed, and the new org clearly alongside it

yes, allowing data to be added to closed organisations makes the data complex to find - so we should block that

**Comment by BlancaTortajada** [comment]
@rossjones yes to all three questions. Re: how to tell users that the organisation is closed and where the new organisation can be found, we can use the [inset text element](http://govuk-elements.herokuapp.com/typography/#typography-inset-text) at the top of the closed org page (if we will have org pages) and on the pages of the datasets belonging to that closed org.

**Comment by BlancaTortajada** [comment]
@rossjones I'll remove the tag "help needed" for now so I have a clearer idea of the things that I need to look into.

**Comment by rossjones** [comment]
I think we can close this, and I'll add a ticket to find to remind us to show closed orgs.
