### ISSUE TITLE
JS tests don't properly delete test datasets

### ISSUE THREAD

**Issue by maxf** [datagovuk/publish_data_alpha#341]

**Comment by rossjones** [comment]
This shouldn't be a problem with test database, we probably need a test search index as well that is cleaned up properly.

**Comment by maxf** [comment]
Working on a new script to start test server, run fe tests, stop server:
https://github.com/datagovuk/publish_data_alpha/pull/345/files
Currently missing command to remove all datasets (and perhaps other things)

**Comment by maxf** [comment]
Fixed with #348
