### ISSUE TITLE
Prevent removing Location from published datasets

### ISSUE THREAD

**Issue by maxf** [datagovuk/publish_data_alpha#389]
and all links, or anything that would prevent a publish dataset from being valid

**Comment by maxf** [comment]
Given that datasets can be published with no location, it's odd that you shouldn't be allowed to remove a location later.
otherwise It's currently not allowed to republish without the minimum needed

**Comment by rossjones** [comment]
All links makes sense.  Removing locations seems like a sensible thing that a user might want to do.  
We currently disallow publishing with no datafiles, so perhaps we can just close this?

**Comment by maxf** [comment]
Agreed. @BlancaTortajada has it on her list, so we can discuss later when we go through it.
