### ISSUE TITLE
URL hash 'sticks'

### ISSUE THREAD

**Issue by maxf** [datagovuk/publish_data_alpha#65]
Steps:
- go to /dataset/new
- fill out title but not description, and submit
- click on 'please provide a description'
- URL is now /dataset/new#id_description_label
- add a description and submit form
- URL becomes /dataset/opkpok1/licence#id_description_label
but the hash should be removed at that point.

**Comment by maxf** [comment]
would be fixed by adding the right action attribute in the form, for instance. Or a redirect.

**Comment by rossjones** [comment]
This is related to #50

**Comment by rossjones** [comment]
Think this is fixed, at least not happening for me anymore.

**Comment by rossjones** [comment]
Same for me too. 

After you POST the response back from /dataset/new it does do a redirect, so I'm not sure how it is keeping hold of the fragment.

**Comment by rossjones** [comment]
This appears to be browser behaviour, and not much we can do about it :(
