### ISSUE TITLE
Form field contents disappear on error

### ISSUE THREAD

**Issue by maxf** [datagovuk/publish_data_alpha#66]
Eg on the title/description form of new datasets, omitting the title and submitting triggers an error but removes the value of fields (valid or invalid).

input values should be value='{{ form.title }}' but currently is value='{{ dataset.title }}'. But the latter works when correcting from the 'check your dataset' page and would break if we did the former.

**Comment by rossjones** [comment]
I should really be filling in the initial data in the form so that you can use {{ form.title }}.  For now, I'd change it to use {{ form.title }} and I'll fix the initial data.

**Comment by rossjones** [comment]
Does this still happen?  Should be fixed I think.

**Comment by maxf** [comment]
Was fixed some time ago
